name: Prueba de Navegación Web

on: [push]

jobs:
  test-navegacion:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Usar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Instalar dependencias
      run: npm install
    
    - name: Iniciar servidor en segundo plano
      run: |
        npm start &
        sleep 5
    
    - name: Instalar navegador y dependencias
      uses: browser-actions/setup-chrome@latest
    
    - name: Probar navegación
      run: |
        chrome --headless --no-sandbox --disable-gpu --screenshot=/tmp/screenshot1.png http://localhost:3000
        chrome --headless --no-sandbox --disable-gpu --screenshot=/tmp/screenshot2.png http://localhost:3000/informacion.html